### PR TITLE
Different Solvers Added

### PR DESCRIPTION
**Pull request by altineel**
1. Even if it is not explicitly stated, I believe the function estimation could/should be done via simulation ? 
2. If the above assumption holds, then should both random and decision nodes call the simulation function and get a value estimate ? 
3. What is the p  value in the table that gives us the epsilon values (Below table) ? I believe it is a hyperparameter but I couldn't find much about it in the paper.
4.  I couldn't figure it out this part of the algorithm . _we construct a new child (i.e. we call the transition function with argu-
ment w)_ Therefore, I end up getting the exception of _Same inducing action has already added as a child._ The issue here is that the if statement here doesn't seem to be checking if all the transition possibilities have visited or not. 

image

Screenshot 2023-03-21 at 14 31 20

### CODE REVIEW

**Comment by larkz** [comment]
First please link this paper,

A few points, 

1) With PUCT, you need to think about what you are going to use as a policy (s, a) -> p and value (V) s-> R estimator. Typically these are done via supervised learning (deep neural net etc.), and updated via reinforcement learning.

2) From my understanding of PUCT, the simulation is not necessarily fully random, but guided by either some value or policy estimotor.

And I also recommend reading the [AlphaGo paper](https://www.nature.com/articles/nature24270), and try to understand the concept. Some key changes,

- What do you plan to use as the V and pi estimators?
- How do we incorporate RL into the picture?
- Can we simplify the policy, given known structures of known policies (for example s,S inventory policy).

I'm afraid I do not understand the rest of your questions, so we should have chat to go over this sometime (perhaps with @mjusup1501 as well).

**Comment by altineel** [comment]
I've implemented the PUCT algorithm but it only visits 2 different actions and I realized that it is no surprise according to algorithm I shared.  If you plug in depthMax = 10 and depth =1, 
the alpha becomes 0.0115 and using this as an expansion parameter in the below equation


Screenshot 2023-04-24 at 12 36 43

we always get  floor(n(z)^0.0115) = floor((n(z)-1)^0.0115) as long as the n(z) =>2   and n(z) < 1billion ...

I've tried smaller numbers instead of multiplier 10 but none of them gave a good expansion tree. Thus, I would be glad if we could think about it.

**Review by JunTaoLuo — APPROVED** [review]

**Comment by larkz** [comment]
please remove all the .xml .iml files from this PR @altineel

**Comment by larkz** [comment]
I tried running this code, and it seems like there's this issue
```
Traceback (most recent call last):
  File "/home/larkin/code/mcts4py/main.py", line 2, in <module>
    from mcts4py.GenericSolver import GenericSolver
  File "/home/larkin/code/mcts4py/mcts4py/GenericSolver.py", line 7, in <module>
    class GenericSolver(MCTSSolver[TAction, ActionNode[TState, TAction, TRandom], RandomNode[TState, TAction, TRandom]], Generic[TState, TAction, TRandom]):
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1345, in __class_getitem__
    _check_generic(cls, params, len(cls.__parameters__))
  File "/usr/lib/python3.10/typing.py", line 231, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
TypeError: Too many arguments for <class 'mcts4py.Nodes.ActionNode'>; actual 3, expected 2
```
Apparently you modified `ActionNode` and others to take 3 args instead of the previous 2, did you propagate this change to the whole codebase?

**Comment by larkz** [comment]
@altineel at the very least run the `main.py` file to ensure that it runs with the previous edition.

**Comment by altineel** [comment]
> 

Sure but there is not `main.py` under the project. It is under the samples/gridwold. I guess you mean that ?

**Comment by larkz** [comment]
> > 
> 
> Sure but there is not `main.py` under the project. It is under the samples/gridwold. I guess you mean that ?

@altineel thanks yes exactly, however, there still seems to be a conflict with the `widening_actions` method

```
Traceback (most recent call last):
  File "/home/larkin/code/mcts4py/main.py", line 10, in <module>
    mdp = GridworldMDP(
TypeError: Can't instantiate abstract class GridworldMDP with abstract method widening_actions
```
Please see address this before merging this code.

**Comment by altineel** [comment]
> > > 
> > 
> > 
> > Sure but there is not `main.py` under the project. It is under the samples/gridwold. I guess you mean that ?
> 
> @altineel thanks yes exactly, however, there still seems to be a conflict with the `widening_actions` method
> 
> ```
> Traceback (most recent call last):
>   File "/home/larkin/code/mcts4py/main.py", line 10, in <module>
>     mdp = GridworldMDP(
> TypeError: Can't instantiate abstract class GridworldMDP with abstract method widening_actions
> ```
> 
> Please see address this before merging this code.

This seems to be a weird error because on the latest push that I've done, there is no `widening_actions` function on the `mdp`class

**Pull request merged**
